apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dg-uc4p2-language-pilot-app-secrets-static-secret
  namespace: zhaw
spec:
  vaultAuthRef: vault-auth-zhaw
  mount: kvv2
  type: kv-v2
  path: zhaw/uc4p2-language-pilot
  destination:
    create: true
    name: dg-uc4p2-language-pilot-app-secrets
